import type { Booth } from "./types";

export const VIEWBOX_WIDTH = 1000;
export const VIEWBOX_HEIGHT = 700;

export const DEFAULT_BOOTHS: Booth[] = [
  {
    id: "main-hall",
    label: "Main Stage",
    category: "Stage",
    x: 300,
    y: 40,
    width: 400,
    height: 180,
    capacity: 500,
    occupancy: 340,
  },
  {
    id: "booth-1",
    label: "TechCorp",
    category: "Sponsor",
    x: 70,
    y: 280,
    width: 200,
    height: 110,
    capacity: 40,
    occupancy: 18,
  },
  {
    id: "booth-2",
    label: "DevTools Inc",
    category: "Sponsor",
    x: 290,
    y: 280,
    width: 200,
    height: 110,
    capacity: 40,
    occupancy: 35,
  },
  {
    id: "booth-3",
    label: "StartupX",
    category: "Startup",
    x: 510,
    y: 280,
    width: 200,
    height: 110,
    capacity: 25,
    occupancy: 10,
  },
  {
    id: "booth-4",
    label: "Foodies Co",
    category: "Food",
    x: 730,
    y: 280,
    width: 200,
    height: 110,
    capacity: 60,
    occupancy: 55,
  },
  {
    id: "booth-5",
    label: "Community Hub",
    category: "Community",
    x: 70,
    y: 420,
    width: 200,
    height: 110,
    capacity: 30,
    occupancy: 12,
  },
  {
    id: "booth-6",
    label: "AI Labs",
    category: "Startup",
    x: 290,
    y: 420,
    width: 200,
    height: 110,
    capacity: 25,
    occupancy: 22,
  },
  {
    id: "booth-7",
    label: "Coffee Corner",
    category: "Food",
    x: 510,
    y: 420,
    width: 200,
    height: 110,
    capacity: 20,
    occupancy: 19,
  },
  {
    id: "booth-8",
    label: "OpenSource Guild",
    category: "Community",
    x: 730,
    y: 420,
    width: 200,
    height: 110,
    capacity: 35,
    occupancy: 8,
  },
];
