#!/bin/bash
# Gas usage profiling script for Gathera contracts
# Addresses Issue #350

set -e

echo "Starting gas usage profiling..."

# Check if run-test.sh exists in the root
if [ -f "./run-test.sh" ]; then
    echo "Running comprehensive gas tests..."
    bash ./run-test.sh --gas-only --benchmark-only --regression-only
else
    echo "run-test.sh not found, trying manual profiling..."
    cd contract
    cargo test --workspace --all-features -- --nocapture | grep -i "gas"
    cd ..
fi

# Ensure reports directory exists
mkdir -p contract/gas_reports

# Copy reports if generated by run-test.sh
if [ -d "reports/gas" ]; then
    cp reports/gas/* contract/gas_reports/
fi

echo "Gas usage profiling completed. Reports available in contract/gas_reports/"
